apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helpdesk-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fedor-Afrin/helpdesk-oci-deploy.git
    targetRevision: main
    path: charts/helpdesk-app # Путь к твоему новому чарту
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Куда будем деплоить само приложение
  syncPolicy:
    automated: # Автоматическая синхронизация (GitOps магия)
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true